[DXP-1399] streamx cloud deloy/delete
streamx-dev/streamx-cli pull request #129
Opened 2024-12-23 17:39 UTC by kamilchociej

## 📋 Type of the Changes

- [ ] Breaking change
- [ ] Non-breaking change
- [ ] Bug fix / minor change

## 🛠 Changes being made

Here give description of the changes you've made in this pull request focusing on what is added or changed. 

For example:

* **Breaking change**: `old-property` renamed to `new-property`.
* **Non-braking change**: Added support for `new-feature`.

## ✅ Checklist

- [ ] My code follows the [code standards](https://github.com/streamx-dev/streamx/blob/main/CONTRIBUTING.md) of this project
- [ ] Changed code is covered with unit tests
- [ ] I have updated READMEs and java docs (if applicable)

2025-01-02 13:20 UTC, kamilchociej commented on core/src/main/java/dev/streamx/cli/command/cloud/CloudCommand.java
> +    description = "Top-level command for cloud operations.",
We won't hide cloud commands.

2025-01-02 13:20 UTC, kamilchociej commented on core/src/main/java/dev/streamx/cli/command/cloud/delete/DeleteCommand.java
> +  public static final String COMMAND_NAME = "delete";
After discussion renamed to undeploy.

2025-01-02 14:40 UTC, michalcukierman approved these changes
Sweet

2025-01-02 14:40 UTC, michalcukierman commented on pom.xml
> +                      <minimum>72%</minimum>
Needed?

2025-01-02 17:13 UTC, jgardo-ds commented on core/src/main/java/dev/streamx/cli/command/cloud/deploy/DeployCommand.java
> +    List<ConfigMap> configMaps = new ArrayList<>();
Extract creation and filling of this list to separate method

2025-01-02 17:13 UTC, jgardo-ds commented on core/src/main/java/dev/streamx/cli/command/cloud/deploy/DeployCommand.java
> +    List<Secret> secrets = new ArrayList<>();
Extract creation and filling of this list to separate method

2025-01-02 17:13 UTC, jgardo-ds commented on core/src/main/java/dev/streamx/cli/command/cloud/undeploy/UndeployCommand.java
> +        + DeployCommand.CLOUD_COMMAND_DESCRIPTION
`Undeploy` - do that with this command, not what this command does.

description is too long. Will be displayed for `stream --help`, where user should see short listing of available commands.

I will verify tomorrow, how to easily display detailed description for `streamx deploy --help`.

2025-01-03 08:17 UTC, kamilchociej commented on core/src/main/java/dev/streamx/cli/command/cloud/undeploy/UndeployCommand.java
> +        + DeployCommand.CLOUD_COMMAND_DESCRIPTION
I can not agree that this description is too long. Take a look on descriptions in other CLI tools 'gcloud' for example.

2025-01-03 08:18 UTC, kamilchociej commented on core/src/main/java/dev/streamx/cli/command/cloud/KubernetesConfig.java
> +  String STREAMX_K8S_NAMESPACE = "namespace";
Refactoring victim. It was `streamx.cloud.namespace` in some point :D

2025-01-03 09:12 UTC, jgardo-ds commented
@kamilchociej Rename please this PR, as it will be commit message.

2025-01-03 09:54 UTC, kamilchociej commented on core/src/main/java/dev/streamx/cli/command/cloud/undeploy/UndeployCommand.java
> +        + DeployCommand.CLOUD_COMMAND_DESCRIPTION
moved to command footer

2025-01-03 11:41 UTC, jgardo-ds requested changes

2025-01-03 11:41 UTC, jgardo-ds commented on core/src/main/java/dev/streamx/cli/command/cloud/deploy/DataService.java
> +        String content = Files.readString(path);
Lines 46-49 and 56-59 are very similar.

It would be great to extract method.

2025-01-03 11:41 UTC, jgardo-ds commented on core/src/main/java/dev/streamx/cli/command/cloud/deploy/DeployCommand.java
> +      The command automatically uses the cluster connection and namespace settings from the \
add new line at begining to separate from previous help content.

2025-01-03 11:41 UTC, jgardo-ds commented on core/src/main/java/dev/streamx/cli/command/cloud/deploy/DeployCommand.java
> +      on the target cluster. If not, please install the operator and ensure the cluster meets \
It would be great to link to resource, how to install the operator (or leave some TODO with ticket number where it will be done)

2025-01-03 11:41 UTC, jgardo-ds commented on core/src/main/java/dev/streamx/cli/command/cloud/deploy/DeployCommand.java
> +    ServiceMesh serviceMesh = serviceMeshService.getServiceMesh(meshPath);
`Service`Mesh `service`mesh = `service`Mesh`Service`.get`Service`Mesh.

2025-01-03 11:41 UTC, jgardo-ds commented on core/src/main/java/dev/streamx/cli/command/cloud/deploy/DeployCommand.java
> +    kubernetesService.deploy(secrets);
It would be useful to log deployed secrets.

It would not be written to stdout but in logs for diagnostics would be useful.

Use injected logger:
```
  @Inject
  Logger log;
```

2025-01-03 11:41 UTC, jgardo-ds commented on core/src/main/java/dev/streamx/cli/command/cloud/deploy/DeployCommand.java
> +    kubernetesService.deploy(configMaps);
as above - log secret names

2025-01-03 11:41 UTC, jgardo-ds commented on core/src/main/java/dev/streamx/cli/exception/KubernetesException.java
> +       \s
Remove if this blank line if you remove it on line 20

2025-01-03 11:41 UTC, jgardo-ds commented on core/src/test/java/dev/streamx/cli/command/cloud/deploy/DataServiceTest.java
> +@QuarkusTest
Basically `DataService` has no dependencies, so `@QuarkusTest` is redundant. (@QuarkusTest is creating quarkus context and so on).
If you disagree, at least change `@QuarkusTest` change to `@QuarkusComponentTest` which by default injects mocks. And runs in miliseconds, not in seconds.


`DataService cut;` can be converted to just `DataService cut = new DataService()`

2025-01-03 11:41 UTC, jgardo-ds commented on core/src/test/java/dev/streamx/cli/command/cloud/deploy/ConfigServiceTest.java
> +@QuarkusTest
In case you are using mocks, you can use `@QuarkusComponentTest` instead of `@QuarkusTest`.

see https://quarkus.io/guides/testing-components

2025-01-03 11:41 UTC, jgardo-ds commented on core/src/test/java/dev/streamx/cli/command/cloud/deploy/DeployCommandIT.java
> +public class DeployCommandIT {
Problem with IT tests is that they are not included in code coverage reports.

It's more global challange, but I suggest renaming it to `DeployCommandTest`.
Or if you want, you can also provide unit test for this class and leave this class as it is.

2025-01-03 11:41 UTC, jgardo-ds commented on core/src/test/java/dev/streamx/cli/command/cloud/deploy/KubernetesServiceTest.java
> +@QuarkusTest
@QuarkusComponentTest

as you are testing only these methods.

2025-01-03 11:41 UTC, jgardo-ds commented on core/src/test/java/dev/streamx/cli/command/cloud/deploy/ProjectResourcesExtractorTest.java
> +@QuarkusTest
@QuarkusComponentTest

2025-01-03 11:45 UTC, kamilchociej commented on core/src/main/java/dev/streamx/cli/command/cloud/KubernetesConfig.java
> +  String STREAMX_K8S_NAMESPACE = "streamx.cloud.namespace";
We are trying to hide k8s relation/dependency kubeconfig will be replaced with streamx cloud auth in the feature

2025-01-03 11:47 UTC, kamilchociej commented on core/src/main/java/dev/streamx/cli/command/cloud/KubernetesConfig.java
> +  @WithName(STREAMX_K8S_NAMESPACE)
Renamed to STREAMX_CLOUD_NAMESPACE

2025-01-03 11:48 UTC, kamilchociej commented on core/src/main/java/dev/streamx/cli/command/cloud/KubernetesService.java
> +  private static void setMetadata(String meshName, Component component, String name,
these methods are static and static methods should be placed before nonstatic

2025-01-03 11:56 UTC, kamilchociej commented on core/src/main/java/dev/streamx/cli/exception/KubernetesException.java
> +  private static final String K8S_CLIENT_EXCEPTION_MESSAGE = """
Double new line before 'Full logs can be found' is inherited from your util. Empty line bofe and after command makes it visible and this is what I was trying to achieve.

2025-01-03 11:58 UTC, kamilchociej commented on core/src/main/java/dev/streamx/cli/exception/KubernetesException.java
> +      * StreamX Operator Custom Resource Definitions are installed on the cluster.
We can add some after we will have documentation.

2025-01-03 12:16 UTC, kamilchociej commented on core/src/main/java/dev/streamx/cli/command/cloud/ServiceMeshService.java
> +      List<String> globalEnvironmentFromConfigs = globalEnvironmentFrom.getConfigs();
It still requires null check for globalEnvironmentFrom

2025-01-03 12:28 UTC, kamilchociej commented on core/src/main/java/dev/streamx/cli/command/cloud/deploy/DeployCommand.java
> +    kubernetesService.deploy(secrets);
Are you crazy? Why would you like to log SECRET data?

2025-01-03 12:30 UTC, kamilchociej commented on core/src/main/java/dev/streamx/cli/command/cloud/deploy/DeployCommand.java
> +    kubernetesService.deploy(configMaps);
Why do you need these names in log? Do you log each message metadata in ingestion command?

2025-01-03 12:40 UTC, michalcukierman commented on core/src/test/java/dev/streamx/cli/command/cloud/deploy/DeployCommandIT.java
> +public class DeployCommandIT {
IT is a correct name for Integration Test.

2025-01-03 12:49 UTC, kamilchociej commented on core/src/test/java/dev/streamx/cli/command/cloud/deploy/DeployCommandIT.java
> +public class DeployCommandIT {
Code coverage above 75% so we can leave it as it is.

2025-01-03 13:22 UTC, jgardo-ds commented on core/src/main/java/dev/streamx/cli/command/cloud/deploy/DeployCommand.java
> +    kubernetesService.deploy(secrets);
are Secret names so secret to even hide its name?

2025-01-03 13:24 UTC, jgardo-ds commented on core/src/main/java/dev/streamx/cli/command/cloud/deploy/DeployCommand.java
> +    kubernetesService.deploy(configMaps);
on startup each service writes all its properties - I think it's good practice to make troubleshooting easier

2025-01-03 13:24 UTC, kamilchociej commented on core/src/test/java/dev/streamx/cli/command/cloud/deploy/DataServiceTest.java
> +@QuarkusTest
Thanks

2025-01-03 13:25 UTC, kamilchociej commented on core/src/test/java/dev/streamx/cli/command/cloud/deploy/ConfigServiceTest.java
> +@QuarkusTest
Thanks

2025-01-03 13:37 UTC, jgardo-ds commented on core/src/main/java/dev/streamx/cli/exception/KubernetesException.java
> +  private static final String K8S_CLIENT_EXCEPTION_MESSAGE = """
so at least add two more spaces before each commands, to make it more visible.

Remove empty line at bottom of text (`"""` should be at end of line 18, not in 19)

2025-01-03 14:27 UTC, jgardo-ds approved these changes

2025-01-03 14:27 UTC, jgardo-ds commented on core/src/test/java/dev/streamx/cli/command/cloud/ProjectPathsResolverTest.java
>  @QuarkusTest
@QuarkusComponentTest?

2025-01-03 14:31 UTC, merged