Dsi 815 java module
streamx-dev/streamx-cli pull request #28
Opened 2024-05-20 14:37 UTC by andrzejmikolajczakds

2024-05-20 15:37 UTC, jgardo-ds commented on e2e-tests/pom.xml
This should be reorganised (see `sortpom-maven-plugin`).

Try `mvn com.github.ekryd.sortpom:sortpom-maven-plugin:sort`.
If it didn't sort anything just move `test` dependencies manually

2024-05-20 15:37 UTC, jgardo-ds commented on e2e-tests/src/test/java/dev/streamx/cli/AppTest.java
> +    private static final String STREAMX_URL = "http://localhost:8081/";
rename STREAMX_URL to WEB_DELIVERY_PORT_URL

You can extract to e.g. @ConfigProperty(name = "streamx.cli.e2e.web-delivery.url")

2024-05-20 15:37 UTC, jgardo-ds commented on e2e-tests/src/test/resources/streamx-mesh.yml
> +      # incoming-assets:
for now you can remove assets configuration - it needs to be implemented in other task

2024-05-20 15:37 UTC, jgardo-ds commented on e2e-tests/src/test/resources/streamx-mesh.yml
> +      # outgoing-assets:
for now you can remove assets configuration - it needs to be implemented in other task

2024-05-20 15:37 UTC, jgardo-ds commented on e2e-tests/src/test/resources/streamx-mesh.yml
> +      # assets:
for now you can remove assets configuration - it needs to be implemented in other task

2024-05-20 15:37 UTC, jgardo-ds commented on .github/workflows/workflows_data/content/file_param_page.json
Sholdn't we remove all content from `.github/workflows/workflows_data?`

2024-05-23 11:38 UTC, andrzejmikolajczakds commented
I will write extra tests in next hour, now please take a look how "framework" for run terminal operation looks like :)

2024-05-24 09:54 UTC, jgardo-ds requested changes

2024-05-24 09:54 UTC, jgardo-ds commented on e2e-tests/src/test/java/dev/streamx/cli/StreamxCliTestsIT.java
> +        60);
expose this timeout as @ConfigProperty - maybe prefixed with "streamx.cli.e2e.setup.timeout"

2024-05-24 09:54 UTC, jgardo-ds commented on e2e-tests/src/test/java/dev/streamx/cli/StreamxCliTestsIT.java
> +  @ConfigProperty(name = "web.delivery.port.url", defaultValue = "http://localhost:8081/")
Prefix this config name with "streamx.cli.e2e"

2024-05-24 09:54 UTC, jgardo-ds commented on e2e-tests/src/main/java/dev/streamx/cli/StreamxCommandProducer.java
> +  @ConfigProperty(name = "streamxCommandType", defaultValue = "built")
Prefix this config name with "streamx.cli.e2e"

2024-05-24 09:54 UTC, jgardo-ds commented on e2e-tests/src/main/java/dev/streamx/cli/StreamxCommandProducer.java
> +public class StreamxCommandProducer {
StreamxTerminalCommandProducer

2024-05-24 09:54 UTC, jgardo-ds commented on e2e-tests/src/test/java/dev/streamx/cli/StreamxCliTestsIT.java
> +  private void streamxCommand(String command, String expectedOutput, long timeoutInS) {
runStreamxCommand

2024-05-24 09:54 UTC, jgardo-ds commented on e2e-tests/src/test/java/dev/streamx/cli/StreamxCliTestsIT.java
> +        2);
move to static final field

2024-05-24 09:54 UTC, jgardo-ds commented on e2e-tests/src/test/java/dev/streamx/cli/StreamxCliTestsIT.java
> +  @Test
These tests looks like dupllicated.
Convert all tests to `ParameterizedTest`
(see example dev.streamx.cli.ingestion.publish.payload.JsonPathExtractorTest#shouldExtractPair)

2024-05-24 09:54 UTC, jgardo-ds commented on e2e-tests/src/test/resources/application.properties
> +web.delivery.port.url=http://localhost:8081/
this will be renamed

2024-05-24 09:54 UTC, jgardo-ds commented on entrypoint/src/test/java/dev/streamx/cli/EntrypointMainTest.java
> +    Assertions.assertTrue(
Thank you, for fixing this :)

2024-05-24 09:54 UTC, jgardo-ds commented on e2e-tests/pom.xml
> +  <name>e2e-tests</name>
other submodules do not have such property - add in other modules such property named:
`StreamX Cli : <uppercased module name with replaced hyphens with spaces>`

So here also change it to   ``<name>StreamX Cli : E2e Tests</name>

2024-05-24 09:54 UTC, jgardo-ds commented on e2e-tests/pom.xml
> +  <dependencies>
reorder dependencies - first production dependencies (used in `src/main` directory) , then test dependencies (used in `src/test`)

2024-05-24 09:54 UTC, jgardo-ds commented on e2e-tests/pom.xml
> +    <pluginManagement>
I suppose it's not critical to list all these plugins. Try to remove whole `<pluginManagement>` and verify if project builds

2024-05-24 09:54 UTC, jgardo-ds commented on e2e-tests/src/main/java/dev/streamx/cli/Config.java
> +@ApplicationScoped
Could it be `@Dependent`?

2024-05-24 09:54 UTC, jgardo-ds commented on e2e-tests/src/main/java/dev/streamx/cli/test/tools/validators/HttpValidator.java
> +      e.printStackTrace();
logger.error?

2024-05-24 09:54 UTC, jgardo-ds commented on e2e-tests/src/main/java/dev/streamx/cli/Config.java
> +  public StreamxCommand streamxCommand(StreamxCommandProducer producer) {
rename `StreamxTerminalCommand` and method name `streamxTerminalCommand`

2024-05-24 09:54 UTC, jgardo-ds commented on e2e-tests/src/test/resources/streamx-mesh.yml
> +defaultImageTag: latest-jvm
This version should be fixed to `streamx.version` from parent pom.
To inject this version here:
1. Add to your e2e pom a <build> tag: 
 ```
    <testResources>
      <testResource>
        <directory>src/main/resources</directory>
        <excludes>
          <exclude>filtered/*</exclude>
        </excludes>
      </testResource>
      <testResource>
        <filtering>true</filtering>
        <directory>src/main/resources/filtered</directory>
        <includes>
          <include>streamx-mesh.yml</include>
        </includes>
      </testResource>
    </testResources>
```
2. Move this file to `src/test/resources/filtered`
3. Replace `defaultImageTag: latest-jvm` with `defaultImageTag: ${streamx.version}-jvm`

2024-05-24 09:56 UTC, andrzejmikolajczakds commented on e2e-tests/src/main/java/dev/streamx/cli/Config.java
> +@ApplicationScoped
I will try :)

2024-05-24 09:56 UTC, andrzejmikolajczakds commented on e2e-tests/src/main/java/dev/streamx/cli/test/tools/validators/HttpValidator.java
> +      e.printStackTrace();
good catch! To much copy paste here :D

2024-05-24 12:43 UTC, jgardo-ds requested changes

2024-05-24 12:43 UTC, jgardo-ds commented on .github/workflows/mvn-build-and-check-streamx-cli-commands-linux.yaml
> +  push:
I think, we should remove this `push`. For now, this will be only manual action.

2024-05-24 12:43 UTC, jgardo-ds commented on core/pom.xml
> +  <name>StreamX Cli : CORE</name>
My bad. I meant not uppercase but capitalised...

So here: `StreamX Cli : Core`

2024-05-24 12:43 UTC, jgardo-ds commented on distribution/pom.xml
> +  <name>StreamX Cli : DISTRIBUTION</name>
My bad. I meant not uppercase but capitalised...

So here: `StreamX Cli : Distribution`

2024-05-24 12:43 UTC, jgardo-ds commented on e2e-tests/pom.xml
> +  <name>StreamX Cli : E2E TESTS</name>
My bad. I meant not uppercase but capitalised...

So here: `StreamX Cli : E2e Tests`

2024-05-24 12:43 UTC, jgardo-ds commented on e2e-tests/pom.xml
> +    <version>0.3.0</version>
0.3.1-SNAPSHOT (after merging main)

2024-05-24 12:43 UTC, jgardo-ds commented on e2e-tests/src/test/java/dev/streamx/cli/StreamxCliTestsIT.java
> +            "-s content.bytes=file://" + absolutePath("json_path_file_param_page.json"),
This file shouldn't be json as content is not json... You can rename this file to `.txt`

2024-05-24 12:43 UTC, jgardo-ds commented on entrypoint/pom.xml
> +  <name>StreamX Cli : ENTRYPOINT</name>
StreamX Cli : Entrypoint

2024-05-24 14:28 UTC, jgardo-ds commented on e2e-tests/src/main/java/dev/streamx/cli/StreamxTerminalCommand.java
> +  String command;
private final

2024-05-24 14:46 UTC, jgardo-ds approved these changes

2024-05-27 07:04 UTC, merged